name: Dave Vigil
title: Dave Vigil

description: A DevOps Engineer from New Mexico, but living in TX

avatar: https://avatars3.githubusercontent.com/u/1594166?v=3&s=466

footer-links:
  facebook: davencindie
  github: dgvigil
  instagram: dgvigil
  twitter: davencindie
  stackoverflow: users/617313/david-vigil

url: http://dgvigil.github.io

permalink: /:title/

version: v1.2.0
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Google Analytics
google_analytics: UA-117416731-1

